/*
*/
accompany_changed(t('0d3d703e'),pen([cc(yellow,1)]),[ac2(trn+0,[iz(cenGX(3))]),ac2(trn+0,[])]). 
accompany_changed(t('0d3d703e'),pen([cc(silver,1)]),[iz(cenGX(2))]). 
accompany_changed(t('0d3d703e'),pen([cc(purple,1)]),[ac2(trn+0,[iz(cenGX(3))]),ac2(trn+0,[])]). 
accompany_changed(t('0d3d703e'),pen([cc(brown,1)]),[iz(sizeGY(3)),iz(cenGY(2)),iz(algo_sid(comp,sid_12)),iz(algo_sid(norm,sid_12)),iz(stype(rectangulator)),iz(stype(hv_line(v))),iz(stype(column)),iz(symmetry_type(rollD,true)),iz(symmetry_type(flipDHV,false)),iz(symmetry_type(rot180,true)),iz(symmetry_type(flipV,true)),iz(symmetry_type(flipH,true)),iz(symmetry_type(rot270,false)),iz(symmetry_type(rot90,false)),iz(symmetry_type(flipD,false)),iz(symmetry_type(sym_h_xor_v,false)),iz(symmetry_type(sym_hv,true)),iz(filltype(solid)),iz(type(colormass)),iz(info(birth(colormass_3))),iz(sid(sid_13))]). 
accompany_changed(t('0d3d703e'),pen([cc(blue,1)]),[ac2(trn+2,[]),loc2D(1,1),iz(cenGX(1))]). 
accompany_changed(t('0d3d703e'),pen([cc(red,1)]),[loc2D(3,1),iz(cenGX(3))]). 
accompany_changed(t('0d3d703e'),pen([cc(cyan,1)]),[iz(cenGX(1))]). 
accompany_changed(t('0d3d703e'),pen([cc(green,1)]),[iz(cenGX(2))]). 
