body_pred(lhs,1).
body_pred(rhs,1).
body_pred(piece,2).
body_pred(contact,2).
body_pred(coord1,2).
body_pred(coord2,2).
body_pred(size,2).

body_pred(red,1).
body_pred(green,1).
body_pred(blue,1).

body_pred(large,1).
body_pred(medium,1).
body_pred(small,1).

body_pred(strange,1).
body_pred(upright,1).

direction(blue,(in,)).
direction(contact,(in,out)).
direction(coord1,(in,out)).
direction(coord2,(in,out)).
direction(green,(in,)).
direction(large,(in,)).
direction(lhs,(in,)).
direction(medium,(in,)).
direction(piece,(in,out)).
direction(red,(in,)).
direction(rhs,(in,)).
direction(size,(in,out)).
direction(small,(in,)).
direction(strange,(in,)).
direction(upright,(in,)).
direction(zendo,(in,)).
head_pred(zendo,1).
type(blue,(piece,)).
type(contact,(piece,piece)).
type(coord1,(piece,real)).
type(coord2,(piece,real)).
type(green,(piece,)).
type(large,(real,)).
type(lhs,(piece,)).
type(medium,(real,)).
type(piece,(state,piece)).
type(red,(piece,)).
type(rhs,(piece,)).
type(size,(piece,real)).
type(small,(real,)).
type(strange,(piece,)).
type(upright,(piece,)).
type(zendo,(state,)).
